/*
  commands/generate_file_pdf.js
  Generates a PDF with an embedded QR for provided text/URL.
*/
const { SlashCommandBuilder, AttachmentBuilder } = require('discord.js');
const QRCode = require('qrcode');
const PDFDocument = require('pdfkit');

module.exports = {
  data: new SlashCommandBuilder()
    .setName('generatefilepdf') // command name (no spaces)
    .setDescription('Generate a PDF containing a QR code for the given text or URL')
    .addStringOption(o => o.setName('input').setDescription('Text or URL to encode').setRequired(true))
    .addStringOption(o => o.setName('title').setDescription('Title for the PDF').setRequired(false)),
  async execute(interaction) {
    await interaction.deferReply();

    const text = interaction.options.getString('input', true);
    const title = interaction.options.getString('title') || 'QR Code';

    try {
      const qrBuffer = await QRCode.toBuffer(text, {
        type: 'png',
        margin: 1,
        width: 400,
        color: { dark: '#000000', light: '#FFFFFF' },
      });

      const doc = new PDFDocument({ autoFirstPage: false });
      const chunks = [];
      doc.on('data', chunk => chunks.push(chunk));
      const endPromise = new Promise((resolve, reject) => {
        doc.on('end', () => resolve(Buffer.concat(chunks)));
        doc.on('error', reject);
      });

      doc.addPage({ size: 'A4', margin: 72 });
      doc.fontSize(22).text(title, { align: 'center' });
      doc.moveDown(1);
      doc.fontSize(12).text(`This PDF contains the QR for: ${text}`, { align: 'center' });
      doc.moveDown(1);

      const imgWidth = 240;
      const imgX = (doc.page.width - imgWidth) / 2;
      doc.image(qrBuffer, imgX, doc.y, { width: imgWidth });

      doc.moveDown(2);
      doc.fontSize(10).text(`Generated by QR-BOT • ${new Date().toLocaleString()}`, { align: 'center' });

      doc.end();
      const pdfBuffer = await endPromise;

      const attachment = new AttachmentBuilder(pdfBuffer, { name: 'qrcode.pdf' });
      await interaction.editReply({ content: `Here is your PDF for: \`${text}\``, files: [attachment] });
    } catch (err) {
      console.error('generatefilepdf error:', err);
      try {
        await interaction.editReply({ content: 'Failed to create PDF. Try again later.' });
      } catch(e) {}
    }
  },
};
