const { SlashCommandBuilder, AttachmentBuilder } = require('discord.js');
const QRCode = require('qrcode');
const PDFDocument = require('pdfkit');

module.exports = {
  data: new SlashCommandBuilder()
    .setName('generatepdf')
    .setDescription('Generate a PDF containing a QR code for the given text/url')
    .addStringOption(o => o.setName('input').setDescription('Text or URL').setRequired(true))
    .addStringOption(o => o.setName('title').setDescription('Title for the PDF').setRequired(false)),
  
  async execute(interaction) {
    await interaction.deferReply(); // give us time

    const text = interaction.options.getString('input', true);
    const title = interaction.options.getString('title') || 'QR Code';

    try {
      // 1) create QR image buffer (PNG)
      const qrBuffer = await QRCode.toBuffer(text, {
        type: 'png',
        margin: 1,
        width: 400,
        color: { dark: '#000000', light: '#FFFFFF' },
      });

      // 2) create PDF in memory using PDFKit
      const doc = new PDFDocument({ autoFirstPage: false });
      const chunks = [];
      doc.on('data', chunk => chunks.push(chunk));
      const endPromise = new Promise((resolve, reject) => {
        doc.on('end', () => resolve(Buffer.concat(chunks)));
        doc.on('error', reject);
      });

      // add a page
      doc.addPage({ size: 'A4', margin: 72 }); // margins in pts
      const pageWidth = doc.page.width - doc.page.margins.left - doc.page.margins.right;

      // Title
      doc.fontSize(22).text(title, { align: 'center' });
      doc.moveDown(1);

      // Add some text / description
      doc.fontSize(12).text(`This PDF contains the QR for: ${text}`, { align: 'center' });
      doc.moveDown(1);

      // Embed QR image centered and scaled
      const imgWidth = 240; // px/points
      const imgX = (doc.page.width - imgWidth) / 2;
      doc.image(qrBuffer, imgX, doc.y, { width: imgWidth });

      // Optionally add footer / timestamp
      doc.moveDown(2);
      doc.fontSize(10).text(`Generated by QR-BOT • ${new Date().toLocaleString()}`, { align: 'center' });

      // finalize
      doc.end();
      const pdfBuffer = await endPromise;

      // Create attachment and reply
      const attachment = new AttachmentBuilder(pdfBuffer, { name: 'qrcode.pdf' });
      await interaction.editReply({ content: `Here is your PDF for: \`${text}\``, files: [attachment] });
    } catch (err) {
      console.error('generatepdf error:', err);
      await interaction.editReply({ content: 'Failed to create PDF. Try again later.' });
    }
  },
};